### PR TITLE
V3.2 changelog / release notes

### PR DESCRIPTION
**Pull request by kbrock**
Release notes for v3.2.0

### CODE REVIEW

**Review by kbrock — COMMENTED** [review]
typically this is just done from the command line and pushed directly into the branch.
so self reviewing / merging.

Thanks all for the hard work.

**Comment by kbrock** [comment]
@adampal @flavorjones I can't merge this. Needs a review from another maintainer.
Can one of you +1 this and then I'll release?

In the future I will skip the PR and see if I can push directly to `master`. (Prefer not to do that but...)

I did try this from the command line but...

```
[master] active_hash $ git push upstream master
remote: Resolving deltas: 100% (8/8), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/zilkey/active_hash.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/zilkey/active_hash.git'
```

heh. Maybe it is my old 'upstream` reference, but I think the protections around `git` may make this difficult.

---

After you are here, could you +1 #254 ? We dropped travis a while ago and that broke local `rake` (default: `rspec`).

Again, I'm not allowed to fix that since I put in the PR.

**Review by flavorjones — APPROVED** [review]

**Comment by rgarver** [comment]
Is this still waiting to go up to Rubygems or is there more to be done? This release seems long overdue, I'm excited to switch to an official version rather than fro.

**Comment by kbrock** [comment]
@rgarver Ryan, thanks for the polite ping.

**Pull request merged**
