### PR TITLE
ActiveHash::Relation: Allow chaining multiples scopes

### PR DESCRIPTION
**Pull request by andreynering**
Closes https://github.com/active-hash/active_hash/issues/247

### CODE REVIEW

**Review by kbrock — COMMENTED** [review]
passes all specs.

I like the idea of adding scopes to the chain.
Not so sure about the `method_missing` approach. But to be honest, that is basically the way scopes are implemented, so I don't see any other way.

Anyone else have an opinion on the `method_missing` and another approach?
If no one does, then I propose merging

**Comment by andreynering** [comment]
@kbrock Yeah, I used `method_missing` because I was out of other ideas on how to implement that.

If anyone has a suggestion, let me know. But this was probably the way to do it.

**Comment by adampal** [comment]
Nice work @andreynering 
I agree that scopes should be chainable so the interface is more consistent with ActiveRecord.

I don't have a better suggestion than what you've done with method missing.  I'm happy to merge this.

**Comment by andreynering** [comment]
Hi @adampal,

Thanks for accepting my contribution! ❤️ 

I'd just like to remind you that you should probably push a new release soon so users can actually use this and other improvements made since the last release, which was a long time ago, about 2 and half years ago.

**Comment by adampal** [comment]
Hey @andreynering no worries, I'll publish a new release shortly. Just wanting to finalise a couple of other pieces first.
I think we'll have the new release ready to go within a week or so.

**Comment by kbrock** [comment]
thanks for the backup review

**Pull request merged**
