### PR TITLE
Migrate from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by ytkg**
Because building on Travis CI is ceased, Migrate to GitHub Actions.

### CODE REVIEW

**Comment by kbrock** [comment]
Someone will need to remove the travis webhook and enable github actions.
If I remember correctly it is a blind jump for the first time but then iteration can continue from there on out

**Comment by tbotaq** [comment]
> Someone will need to remove the travis webhook

Is it anybody that is authorized to visit this page ? (I'm not certain && I'm not authorized)
https://travis-ci.org/zilkey/active_hash

---

> and enable github actions.

Is it anybody listed in the following list ? (I'm not certain)
https://github.com/orgs/active-hash/people

**Comment by kbrock** [comment]
Specifically, the pages are:
- https://github.com/ManageIQ/query_relation/settings/actions
- https://github.com/ManageIQ/query_relation/settings/hooks

Right now, we will probably be content just running the tests locally, but that puts more burden on the mergers.

I think @adampal is the only one who can change the settings, though I have no real way of determining the users with admin access to this repo.

---

Adam,

If you can, could you spare some cycles and enable github actions?
Travis.org would probably like it if you drop the travis web hooks

Thanks

**Comment by kbrock** [comment]
@ytkg Could you peek at [my travis.yml](https://github.com/active-hash/active_hash/pull/246) and update our matrix here?

Looks like there is a minor conflict in `README.md` as well.

**Comment by ytkg** [comment]
I'd like to update matrix after that PR is merged. Is that okay?

**Comment by kbrock** [comment]
@ytkg to be honest, we still do not have a plan for getting your PR merged. no one with privs to modify the settings is around

**Comment by kbrock** [comment]
@adampal Hi. Are you able to help us go across to github actions?

If you flip those switches I will be more than happy to followup and get this all flowing. It is the admin stuff that most of the mergers do not have access to do.

**Comment by adampal** [comment]
@kbrock and @ytkg apologies for holding you up here.  I've merged this commit and removed the travis web hook.  @kbrock the settings under the actions page you linked to look ok to me, but if there's a change we need to make just let me know.
From what I can see, this looks like it's triggered a GitHub action. We can watch it and see!

**Comment by ytkg** [comment]
thank you!

**Pull request merged**
