### PR TITLE
version bump to v3.3.1

### PR DESCRIPTION
**Pull request by flavorjones**
I'm happy to make the release once this is approved and merged.

### CODE REVIEW

**Review by kbrock — APPROVED** [review]
LGTM

@flavorjones you need me to release or you have this?

**Comment by kbrock** [comment]
darn. thought this was in 3.3.

Thanks

**Comment by flavorjones** [comment]
@kbrock I'll ship the release today!

**Comment by flavorjones** [comment]
Done: https://github.com/active-hash/active_hash/releases/tag/v3.3.1

**Pull request merged**
